20-rails-associations/gamify-many/config/routes.rb
Rails.application.routes.draw do
  resources :players
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get '/game/:slug', to: 'games#show'

  resources :games

  # post '/search', to: 'games#search'
  # delete '/games/:id', to: 'games#destroy'
end

20-rails-associations/gamify-many/app/models/game.rb
class Game < ApplicationRecord
	has_many :games_players
	has_many :players, through: :games_players

	validates :title, presence: true
end

20-rails-associations/gamify-many/app/models/games_player.rb
class GamesPlayer < ApplicationRecord
  belongs_to :game
  belongs_to :player
end

20-rails-associations/gamify-many/app/models/player.rb
class Player < ApplicationRecord
	has_many :games_players
	has_many :games, through: :games_players
end

20-rails-associations/gamify-many/app/controllers/games_controller.rb
class GamesController < ApplicationController
	before_action :find_game, only: [:show, :edit, :destroy, :update]

	def index
		@games = Game.all
	end

	def show
		# @game = Game.find(params[:id])
	end

	def edit
	end

	def new
		@game = Game.new
	end

	def create
		@game = Game.new(game_params)

		if @game.save
			redirect_to @game
		else
			render :new
		end
	end

	def update
		if @game.update(game_params)
			redirect_to @game
		else
			render :edit
		end
	end

	def destroy
		# @game = Game.find(params[:id])
		@game.destroy

		redirect_to games_path
	end

	private
	def game_params
		params.require(:game).permit(:title, :image_url, :description)
	end

	def find_game
		@game = Game.find(params[:id])
	end
end

20-rails-associations/gamify-many/app/controllers/players_controller.rb
class PlayersController < ApplicationController
end

20-rails-associations/gamify-many/app/helpers/games_helper.rb
module GamesHelper
end

20-rails-associations/gamify-many/app/helpers/players_helper.rb
module PlayersHelper
end

20-rails-associations/gamify-many/app/views/games/edit.html.erb
<h1>Update game</h1>

<% if @game.errors.any? %>
	<ul>
	<% @game.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
	</ul>
<% end %>

<%= form_with model: @game, local: true do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :description %>
	<%= f.text_area :description %>
	
	<%= f.label :image_url %>
	<%= f.text_field :image_url %>

  <%= f.submit "Update Game" %>
<% end %>

20-rails-associations/gamify-many/app/views/games/index.html.erb
<h1>All Games</h1>

<div class="games">
	<% @games.each do |game| %>
		<div>
			<img src="<%= game.image_url %>" alt="">
			<%= link_to game.title, game, class: "title" %>
			<div class="description"><%= game.description %></div>
		</div>
	<% end %>
</div>

20-rails-associations/gamify-many/app/views/games/new.html.erb
<h1>Create a new game</h1>

<!-- show error messages -->

<% if @game.errors.any? %>
	<ul>
	<% @game.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
	</ul>
<% end %>

<%= form_for @game do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :description %>
	<%= f.text_area :description %>
	
	<%= f.label :image_url %>
	<%= f.text_field :image_url %>

  <%= f.submit "Create new Game" %>
<% end %>


<!-- <%#= form_with model: @game, local: true do |f| %>
	<%#= f.label :title %>
	<%#= f.text_field :title %>

	<%#= f.label :description %>
	<%#= f.text_area :description %>
	
	<%#= f.label :image_url %>
	<%#= f.text_field :image_url %>

  <%#= f.submit "Create new Game" %>
<%# end %> -->

<!-- <%#= form_with(url: "/search", method: "post") do %>
  <%#= label_tag(:q, "Search for:") %>
  <%#= text_field_tag(:q) %>
  <%#= submit_tag("Search") %>
<%# end %> -->

20-rails-associations/gamify-many/app/views/games/show.html.erb
<h1><%= @game.title %></h1>
<img src="<%= @game.image_url %>" alt="">
<p><%= @game.description %></p>


<% @game.players.map do |player| %>
	<%= link_to player.name, player_path(player) %>
<% end %>

<%= link_to "Edit", edit_game_path(@game), class: "button" %>
<%= link_to "Delete", game_path(@game), method: "delete", class: "button" %>

20-rails-associations/gamify-many/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link
      href="https://fonts.googleapis.com/css?family=Josefin+Sans|Press+Start+2P&display=swap"
      rel="stylesheet"
    />
  </head>

  <body>
    <nav>
      <a href="/">Home</a>
      <a href="/games">All Games</a>
      <a href="/games/new">New Game</a>
    </nav>
    
    <main>
      <%= yield %>
    </main>
  </body>
</html>